# Ensure the namespace has been labelled with namespace=internal
# kubectl get ns
# kubectl describe ns app-team1
# kubectl label ns app-team1 namespace=internal 

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-port-from-namespace
  namespace: echo
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          namespace: internal
    ports:
    - protocol: TCP
      port: 9200


