apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: alpine:latest
          command: ['sh', '-c', 'while true; do echo "logging" >> /var/log/big-corp-app.log; sleep 1; done']
          volumeMounts:
            - name: data
              mountPath: /var/log
        - name: sidecar
          image: busybox
          command: ['/bin/sh', '-c', 'tail -n+1 -f /var/log/big-corp-app.log']
          volumeMounts:
            - name: data
              mountPath: /var/log
      volumes:
        - name: data
          emptyDir: {}