# Run in bash

kubectl edit deployment front-end

apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  labels:
    app: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          name: http

# create a new service
# Better avoid this.
kubectl create service nodeport front-end-svc --tcp=80

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-10-08T13:45:20Z"
  labels:
    app: front-end
  name: front-end
  namespace: default
  resourceVersion: "449484"
  uid: e481517d-43a0-465a-85ae-0cd6e7c1ddb2
spec:
  clusterIP: 10.98.248.118
  clusterIPs:
  - 10.98.248.118
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: "80"
    nodePort: 31729
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: front-end
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

# Try use this
kubectl expose deployment front-end-svc --type="NodePort" --port 80
