
# Create a pod

apiVersion: v1
kind: Pod
metadata:
  name: kucc8
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: consul
    image: consul:latest
    ports:
    - containerPort: 80
