apiVersion: v1
kind: Pod
metadata:
  name: kucc8
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  - name: consul
    image: consul
    ports:
    - containerPort: 81
