apiVersion: v1
kind: Pod
metadata:
  name: broken-indentation-pod
    namespace: default
  labels:
      app: nginx
    tier: frontend
spec:
    containers:
  - name: nginx-container
      image: nginx:1.21
    ports:
      - containerPort: 80
        protocol: TCP
      resources:
    requests:
          memory: "64Mi"
        cpu: "250m"
      limits:
          memory: "128Mi"
    cpu: "500m"
    env:
  - name: ENV_VAR
        value: "some-value"
      - name: ANOTHER_VAR
    value: "another-value"
  restartPolicy: Always
    dnsPolicy: ClusterFirst
